map filter checkbox and css
WildCodeSchool/nts-js-202103-p2-recyclage pull request #15
Opened 2021-04-24 11:23 UTC by Maxencergn

2021-04-24 19:18 UTC, n-germain-work approved these changes

2021-04-25 19:00 UTC, bastienwcs requested changes

2021-04-25 19:00 UTC, bastienwcs commented on src/components/CollectMap.jsx
> +            /* .filter(
ce code servira plus tard ? ou faut-il le supprimer ?

2021-04-26 07:16 UTC, Maxencergn commented on src/components/CollectMap.jsx
> +            /* .filter(
oui je l'ai laissé car on va peut-être s'en reservir !

2021-04-26 07:37 UTC, bastienwcs commented on src/components/CollectMap.jsx
> +            /* .filter(
dans ce cas-là, tu peux en faire un gist : https://gist.github.com/
et le supprimer du code source :)

2021-04-26 08:48 UTC, Maxencergn commented on src/components/CollectMap.jsx
> +            /* .filter(
je viens de le supprimer ! :)

2021-04-26 09:21 UTC, bastienwcs approved these changes

2021-04-26 21:14 UTC, merged