map component and filter checkbox fonctionnel
WildCodeSchool/nts-js-202103-p2-recyclage pull request #16
Opened 2021-04-27 08:39 UTC by Maxencergn

2021-04-27 13:15 UTC, NinonMaraval commented on src/components/CollectMap.jsx
>                      {/* eslint-disable-next-line jsx-a11y/label-has-associated-control */}
tu peux t'en passer ;-)

2021-04-27 13:15 UTC, NinonMaraval commented on src/components/CollectMap.jsx
>                      {/* eslint-disable-next-line jsx-a11y/label-has-associated-control */}
same here :)

2021-04-27 13:16 UTC, NinonMaraval commented on src/components/CollectMap.jsx
>                      {/* eslint-disable-next-line jsx-a11y/label-has-associated-control */}
pareil ici :)

2021-04-27 13:16 UTC, NinonMaraval commented on src/components/CollectMap.jsx
>                      {/* eslint-disable-next-line jsx-a11y/label-has-associated-control */}
encore !!!!!! mais...

2021-04-27 13:16 UTC, NinonMaraval commented on src/components/CollectMap.jsx
>                      {/* eslint-disable-next-line jsx-a11y/label-has-associated-control */}
je vais me fâcher

2021-04-27 13:16 UTC, NinonMaraval commented on src/components/CollectMap.jsx
> +                    {/* eslint-disable-next-line jsx-a11y/label-has-associated-control */}
tout rouge

2021-04-27 13:18 UTC, NinonMaraval commented on src/components/CollectMap.jsx
> +                    {/* eslint-disable-next-line jsx-a11y/label-has-associated-control */}
idem ici mais Nico verra avec toi

2021-04-27 13:19 UTC, NinonMaraval requested changes
code à corriger pour ne pas avoir besoin d'utiliser eslint

2021-04-28 07:29 UTC, NinonMaraval approved these changes
tout ok pour moi !

2021-04-28 07:31 UTC, bastienwcs approved these changes

2021-04-28 07:32 UTC, merged